// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Bs_dom_wrapper_event_target = require("./bs_dom_wrapper_event_target.js");

function Make(T) {
  Bs_dom_wrapper_event_target.Make(T);
  return /* module */[];
}

var T = /* module */[];

Bs_dom_wrapper_event_target.Make(T);

exports.Make = Make;
/*  Not a pure module */
