// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


function to_string(param) {
  if (param !== 0) {
    return "submit";
  } else {
    return "DOMContentLoaded";
  }
}

var Event_type = /* module */[/* to_string */to_string];

exports.Event_type = Event_type;
/* No side effect */
