// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Bs_dom_wrapper_event = require("./bs_dom_wrapper_event.js");

var Event = /* module */[
  /* Make */Bs_dom_wrapper_event.Make,
  /* Progress_event */0
];

var File = /* module */[];

var FormData = /* module */[];

var Node = /* module */[];

var Image_element = /* module */[];

var Canvas_context = /* module */[];

var Canvas_element = /* module */[];

var FileReader = /* module */[];

exports.Event          = Event;
exports.File           = File;
exports.FormData       = FormData;
exports.Node           = Node;
exports.Image_element  = Image_element;
exports.Canvas_context = Canvas_context;
exports.Canvas_element = Canvas_element;
exports.FileReader     = FileReader;
/* No side effect */
