// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Bs_dom_wrapper_event = require("./bs_dom_wrapper_event.js");

Bs_dom_wrapper_event.Make(/* module */[]);

/*  Not a pure module */
